#pragma once
#include "gui/defines.h"

/* THIS FILE WAS AUTOGENERATED ON 8/23/2022 7:22:07 PM */

extern const gfx_font_t font_system_14;
extern const gfx_img_t icon_alert_warn;
extern const gfx_img_t icon_recorder_iq;
extern const gfx_img_t icon_recorder_warn;
extern const gfx_img_t icon_sdcard;
extern const gfx_img_t icon_sdcard_error;
extern const gfx_img_t icon_sdcard_none;
extern const gfx_img_t icon_sdcard_waiting;
