#pragma once
#include "gui/defines.h"

/* THIS FILE WAS AUTOGENERATED ON 8/17/2022 11:37:48 PM */

extern const gfx_font_t font_system_14;
extern const gfx_img_t icon_sdcard;
extern const gfx_img_t icon_sdcard_error;
extern const gfx_img_t icon_sdcard_none;
extern const gfx_img_t icon_sdcard_waiting;
