#include "gui/assets.h"
#include "gui/display.h"

/* THIS FILE WAS AUTOGENERATED ON 8/17/2022 11:37:48 PM */

static const uint64_t lambda0_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda0 = {
    .data = lambda0_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda1_data[] = {
    0x000003F8,
    0x00000404,
    0x00000494,
    0x00000584,
    0x00000584,
    0x00000494,
    0x00000404,
    0x000003F8,
    0x00000000
};
static const gfx_img_t lambda1 = {
    .data = lambda1_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda2_data[] = {
    0x000003F8,
    0x000007FC,
    0x0000076C,
    0x0000067C,
    0x0000067C,
    0x0000076C,
    0x000007FC,
    0x000003F8,
    0x00000000
};
static const gfx_img_t lambda2 = {
    .data = lambda2_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda3_data[] = {
    0x00000000,
    0x000000F0,
    0x000001F8,
    0x000003F8,
    0x000007F0,
    0x000003F8,
    0x000001F8,
    0x000000F0,
    0x00000000
};
static const gfx_img_t lambda3 = {
    .data = lambda3_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda4_data[] = {
    0x00000000,
    0x00000040,
    0x000000E0,
    0x000001F0,
    0x000003F8,
    0x000001F0,
    0x000000E0,
    0x00000040,
    0x00000000
};
static const gfx_img_t lambda4 = {
    .data = lambda4_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda5_data[] = {
    0x000000E0,
    0x000000E0,
    0x000004F8,
    0x0000071C,
    0x0000071C,
    0x000004F8,
    0x000000E0,
    0x000000E0,
    0x00000000
};
static const gfx_img_t lambda5 = {
    .data = lambda5_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda6_data[] = {
    0x00000060,
    0x000000F0,
    0x000004F8,
    0x000007FC,
    0x000007FC,
    0x000004F8,
    0x000000F0,
    0x00000060,
    0x00000000
};
static const gfx_img_t lambda6 = {
    .data = lambda6_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda7_data[] = {
    0x00000000,
    0x00000000,
    0x000000C0,
    0x000001E0,
    0x000001E0,
    0x000000C0,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda7 = {
    .data = lambda7_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda8_data[] = {
    0x00003FFF,
    0x00003FFF,
    0x00003F3F,
    0x00003E1F,
    0x00003E1F,
    0x00003F3F,
    0x00003FFF,
    0x00003FFF,
    0x00000000
};
static const gfx_img_t lambda8 = {
    .data = lambda8_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda9_data[] = {
    0x00000000,
    0x000001E0,
    0x00000330,
    0x00000210,
    0x00000210,
    0x00000330,
    0x000001E0,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda9 = {
    .data = lambda9_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda10_data[] = {
    0x00003FFF,
    0x00003E1F,
    0x00003CCF,
    0x00003DEF,
    0x00003DEF,
    0x00003CCF,
    0x00003E1F,
    0x00003FFF,
    0x00000000
};
static const gfx_img_t lambda10 = {
    .data = lambda10_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda11_data[] = {
    0x00000000,
    0x00000380,
    0x000007C0,
    0x00000460,
    0x00000474,
    0x000007DC,
    0x0000038C,
    0x0000003C,
    0x00000000
};
static const gfx_img_t lambda11 = {
    .data = lambda11_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda12_data[] = {
    0x00000000,
    0x00000138,
    0x0000017C,
    0x000007C4,
    0x000007C4,
    0x0000017C,
    0x00000138,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda12 = {
    .data = lambda12_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda13_data[] = {
    0x00000600,
    0x00000700,
    0x000007FC,
    0x000003FC,
    0x00000014,
    0x00000014,
    0x0000001C,
    0x0000001C,
    0x00000000
};
static const gfx_img_t lambda13 = {
    .data = lambda13_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda14_data[] = {
    0x00000E00,
    0x00000FFC,
    0x000007FC,
    0x00000014,
    0x00000014,
    0x00000714,
    0x000007FC,
    0x000003FC,
    0x00000000
};
static const gfx_img_t lambda14 = {
    .data = lambda14_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda15_data[] = {
    0x00000150,
    0x00000150,
    0x000000E0,
    0x000007BC,
    0x000007BC,
    0x000000E0,
    0x00000150,
    0x00000150,
    0x00000000
};
static const gfx_img_t lambda15 = {
    .data = lambda15_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda16_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda16 = {
    .data = lambda16_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda17_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda17 = {
    .data = lambda17_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda18_data[] = {
    0x00000000,
    0x00000110,
    0x00000318,
    0x000007FC,
    0x000007FC,
    0x00000318,
    0x00000110,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda18 = {
    .data = lambda18_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda19_data[] = {
    0x00000000,
    0x00000000,
    0x000006FC,
    0x000006FC,
    0x00000000,
    0x00000000,
    0x000006FC,
    0x000006FC,
    0x00000000
};
static const gfx_img_t lambda19 = {
    .data = lambda19_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda20_data[] = {
    0x00000038,
    0x0000007C,
    0x00000044,
    0x000007FC,
    0x000007FC,
    0x00000004,
    0x000007FC,
    0x000007FC,
    0x00000000
};
static const gfx_img_t lambda20 = {
    .data = lambda20_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda21_data[] = {
    0x00000000,
    0x000008C4,
    0x000019EE,
    0x0000133A,
    0x00001212,
    0x00001732,
    0x00001DE6,
    0x000008C4,
    0x00000000
};
static const gfx_img_t lambda21 = {
    .data = lambda21_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda22_data[] = {
    0x00000000,
    0x00000700,
    0x00000700,
    0x00000700,
    0x00000700,
    0x00000700,
    0x00000700,
    0x00000700,
    0x00000000
};
static const gfx_img_t lambda22 = {
    .data = lambda22_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda23_data[] = {
    0x00000000,
    0x00000910,
    0x00000B18,
    0x00000FFC,
    0x00000FFC,
    0x00000B18,
    0x00000910,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda23 = {
    .data = lambda23_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda24_data[] = {
    0x00000000,
    0x00000010,
    0x00000018,
    0x000007FC,
    0x000007FC,
    0x00000018,
    0x00000010,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda24 = {
    .data = lambda24_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda25_data[] = {
    0x00000000,
    0x00000100,
    0x00000300,
    0x000007FC,
    0x000007FC,
    0x00000300,
    0x00000100,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda25 = {
    .data = lambda25_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda26_data[] = {
    0x00000000,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000150,
    0x000001F0,
    0x000000E0,
    0x00000040,
    0x00000000
};
static const gfx_img_t lambda26 = {
    .data = lambda26_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda27_data[] = {
    0x00000000,
    0x00000040,
    0x000000E0,
    0x000001F0,
    0x00000150,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000000
};
static const gfx_img_t lambda27 = {
    .data = lambda27_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda28_data[] = {
    0x00000000,
    0x000001E0,
    0x000001E0,
    0x00000100,
    0x00000100,
    0x00000100,
    0x00000100,
    0x00000100,
    0x00000000
};
static const gfx_img_t lambda28 = {
    .data = lambda28_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda29_data[] = {
    0x00000040,
    0x000000E0,
    0x000001F0,
    0x00000040,
    0x00000040,
    0x000001F0,
    0x000000E0,
    0x00000040,
    0x00000000
};
static const gfx_img_t lambda29 = {
    .data = lambda29_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda30_data[] = {
    0x00000000,
    0x00000300,
    0x000003C0,
    0x000003F0,
    0x000003F8,
    0x000003F0,
    0x000003C0,
    0x00000300,
    0x00000000
};
static const gfx_img_t lambda30 = {
    .data = lambda30_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda31_data[] = {
    0x00000000,
    0x00000018,
    0x00000078,
    0x000001F8,
    0x000003F8,
    0x000001F8,
    0x00000078,
    0x00000018,
    0x00000000
};
static const gfx_img_t lambda31 = {
    .data = lambda31_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda32_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda32 = {
    .data = lambda32_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda33_data[] = {
    0x00000000,
    0x00000000,
    0x00000038,
    0x000006FC,
    0x000006FC,
    0x00000038,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda33 = {
    .data = lambda33_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda34_data[] = {
    0x00000000,
    0x0000000E,
    0x0000001E,
    0x00000000,
    0x00000000,
    0x00000000,
    0x0000001E,
    0x0000000E,
    0x00000000
};
static const gfx_img_t lambda34 = {
    .data = lambda34_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda35_data[] = {
    0x00000000,
    0x00000110,
    0x000007FC,
    0x000007FC,
    0x00000110,
    0x000007FC,
    0x000007FC,
    0x00000110,
    0x00000000
};
static const gfx_img_t lambda35 = {
    .data = lambda35_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda36_data[] = {
    0x00000000,
    0x00000338,
    0x0000067C,
    0x00000444,
    0x00001C47,
    0x00001C47,
    0x000007CC,
    0x00000398,
    0x00000000
};
static const gfx_img_t lambda36 = {
    .data = lambda36_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda37_data[] = {
    0x00000000,
    0x00000430,
    0x00000630,
    0x00000300,
    0x00000180,
    0x000000C0,
    0x00000660,
    0x00000630,
    0x00000000
};
static const gfx_img_t lambda37 = {
    .data = lambda37_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda38_data[] = {
    0x00000000,
    0x00000380,
    0x000007D8,
    0x0000047C,
    0x000004E4,
    0x000003BC,
    0x000007D8,
    0x00000440,
    0x00000000
};
static const gfx_img_t lambda38 = {
    .data = lambda38_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda39_data[] = {
    0x00000000,
    0x00000010,
    0x0000001E,
    0x0000000E,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda39 = {
    .data = lambda39_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda40_data[] = {
    0x00000000,
    0x00000000,
    0x000001F0,
    0x000003F8,
    0x0000060C,
    0x00000404,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda40 = {
    .data = lambda40_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda41_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000404,
    0x0000060C,
    0x000003F8,
    0x000001F0,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda41 = {
    .data = lambda41_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda42_data[] = {
    0x00000040,
    0x00000150,
    0x000001F0,
    0x000000E0,
    0x000000E0,
    0x000001F0,
    0x00000150,
    0x00000040,
    0x00000000
};
static const gfx_img_t lambda42 = {
    .data = lambda42_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda43_data[] = {
    0x00000040,
    0x00000040,
    0x00000040,
    0x000003F8,
    0x000003F8,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000000
};
static const gfx_img_t lambda43 = {
    .data = lambda43_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda44_data[] = {
    0x00000000,
    0x00000000,
    0x00000800,
    0x00000F00,
    0x00000700,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda44 = {
    .data = lambda44_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda45_data[] = {
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000000
};
static const gfx_img_t lambda45 = {
    .data = lambda45_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda46_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000600,
    0x00000600,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda46 = {
    .data = lambda46_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda47_data[] = {
    0x00000000,
    0x00000300,
    0x00000180,
    0x000000C0,
    0x00000060,
    0x00000030,
    0x00000018,
    0x0000000C,
    0x00000000
};
static const gfx_img_t lambda47 = {
    .data = lambda47_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda48_data[] = {
    0x00000000,
    0x000003F8,
    0x000007FC,
    0x000004C4,
    0x00000464,
    0x00000434,
    0x000007FC,
    0x000003F8,
    0x00000000
};
static const gfx_img_t lambda48 = {
    .data = lambda48_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda49_data[] = {
    0x00000000,
    0x00000000,
    0x00000410,
    0x00000418,
    0x000007FC,
    0x000007FC,
    0x00000400,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda49 = {
    .data = lambda49_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda50_data[] = {
    0x00000000,
    0x00000608,
    0x0000070C,
    0x00000584,
    0x000004C4,
    0x00000464,
    0x0000063C,
    0x00000618,
    0x00000000
};
static const gfx_img_t lambda50 = {
    .data = lambda50_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda51_data[] = {
    0x00000000,
    0x00000208,
    0x0000060C,
    0x00000444,
    0x00000444,
    0x00000444,
    0x000007FC,
    0x000003B8,
    0x00000000
};
static const gfx_img_t lambda51 = {
    .data = lambda51_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda52_data[] = {
    0x00000000,
    0x000000C0,
    0x000000E0,
    0x000000B0,
    0x00000498,
    0x000007FC,
    0x000007FC,
    0x00000480,
    0x00000000
};
static const gfx_img_t lambda52 = {
    .data = lambda52_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda53_data[] = {
    0x00000000,
    0x0000027C,
    0x0000067C,
    0x00000444,
    0x00000444,
    0x00000444,
    0x000007C4,
    0x00000384,
    0x00000000
};
static const gfx_img_t lambda53 = {
    .data = lambda53_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda54_data[] = {
    0x00000000,
    0x000003F0,
    0x000007F8,
    0x0000044C,
    0x00000444,
    0x00000444,
    0x000007C0,
    0x00000380,
    0x00000000
};
static const gfx_img_t lambda54 = {
    .data = lambda54_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda55_data[] = {
    0x00000000,
    0x0000000C,
    0x0000000C,
    0x00000784,
    0x000007C4,
    0x00000064,
    0x0000003C,
    0x0000001C,
    0x00000000
};
static const gfx_img_t lambda55 = {
    .data = lambda55_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda56_data[] = {
    0x00000000,
    0x000003B8,
    0x000007FC,
    0x00000444,
    0x00000444,
    0x00000444,
    0x000007FC,
    0x000003B8,
    0x00000000
};
static const gfx_img_t lambda56 = {
    .data = lambda56_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda57_data[] = {
    0x00000000,
    0x00000038,
    0x0000047C,
    0x00000444,
    0x00000444,
    0x00000644,
    0x000003FC,
    0x000001F8,
    0x00000000
};
static const gfx_img_t lambda57 = {
    .data = lambda57_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda58_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000318,
    0x00000318,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda58 = {
    .data = lambda58_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda59_data[] = {
    0x00000000,
    0x00000000,
    0x00000400,
    0x00000718,
    0x00000318,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda59 = {
    .data = lambda59_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda60_data[] = {
    0x00000000,
    0x00000040,
    0x000000E0,
    0x000001B0,
    0x00000318,
    0x0000060C,
    0x00000404,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda60 = {
    .data = lambda60_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda61_data[] = {
    0x00000000,
    0x00000120,
    0x00000120,
    0x00000120,
    0x00000120,
    0x00000120,
    0x00000120,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda61 = {
    .data = lambda61_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda62_data[] = {
    0x00000000,
    0x00000404,
    0x0000060C,
    0x00000318,
    0x000001B0,
    0x000000E0,
    0x00000040,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda62 = {
    .data = lambda62_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda63_data[] = {
    0x00000000,
    0x00000018,
    0x0000001C,
    0x00000004,
    0x000006C4,
    0x000006E4,
    0x0000003C,
    0x00000018,
    0x00000000
};
static const gfx_img_t lambda63 = {
    .data = lambda63_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda64_data[] = {
    0x00000000,
    0x000003F8,
    0x000007FC,
    0x00000404,
    0x000005E4,
    0x000005E4,
    0x000005FC,
    0x000000F8,
    0x00000000
};
static const gfx_img_t lambda64 = {
    .data = lambda64_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda65_data[] = {
    0x00000000,
    0x000007E0,
    0x000007F0,
    0x00000098,
    0x0000008C,
    0x00000098,
    0x000007F0,
    0x000007E0,
    0x00000000
};
static const gfx_img_t lambda65 = {
    .data = lambda65_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda66_data[] = {
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000444,
    0x00000444,
    0x000007FC,
    0x000003B8,
    0x00000000
};
static const gfx_img_t lambda66 = {
    .data = lambda66_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda67_data[] = {
    0x00000000,
    0x000001F0,
    0x000003F8,
    0x0000060C,
    0x00000404,
    0x00000404,
    0x0000060C,
    0x00000318,
    0x00000000
};
static const gfx_img_t lambda67 = {
    .data = lambda67_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda68_data[] = {
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000404,
    0x0000060C,
    0x000003F8,
    0x000001F0,
    0x00000000
};
static const gfx_img_t lambda68 = {
    .data = lambda68_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda69_data[] = {
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000444,
    0x000004E4,
    0x0000060C,
    0x0000071C,
    0x00000000
};
static const gfx_img_t lambda69 = {
    .data = lambda69_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda70_data[] = {
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000444,
    0x000000E4,
    0x0000000C,
    0x0000001C,
    0x00000000
};
static const gfx_img_t lambda70 = {
    .data = lambda70_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda71_data[] = {
    0x00000000,
    0x000001F0,
    0x000003F8,
    0x0000060C,
    0x00000484,
    0x00000484,
    0x0000038C,
    0x00000798,
    0x00000000
};
static const gfx_img_t lambda71 = {
    .data = lambda71_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda72_data[] = {
    0x00000000,
    0x000007FC,
    0x000007FC,
    0x00000040,
    0x00000040,
    0x00000040,
    0x000007FC,
    0x000007FC,
    0x00000000
};
static const gfx_img_t lambda72 = {
    .data = lambda72_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda73_data[] = {
    0x00000000,
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000404,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda73 = {
    .data = lambda73_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda74_data[] = {
    0x00000000,
    0x00000300,
    0x00000700,
    0x00000400,
    0x00000404,
    0x000007FC,
    0x000003FC,
    0x00000004,
    0x00000000
};
static const gfx_img_t lambda74 = {
    .data = lambda74_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda75_data[] = {
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000040,
    0x000001F0,
    0x000007BC,
    0x0000060C,
    0x00000000
};
static const gfx_img_t lambda75 = {
    .data = lambda75_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda76_data[] = {
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000404,
    0x00000400,
    0x00000600,
    0x00000700,
    0x00000000
};
static const gfx_img_t lambda76 = {
    .data = lambda76_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda77_data[] = {
    0x000007FC,
    0x000007FC,
    0x00000018,
    0x00000030,
    0x00000030,
    0x00000018,
    0x000007FC,
    0x000007FC,
    0x00000000
};
static const gfx_img_t lambda77 = {
    .data = lambda77_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda78_data[] = {
    0x00000000,
    0x000007FC,
    0x000007FC,
    0x00000038,
    0x00000070,
    0x000000E0,
    0x000007FC,
    0x000007FC,
    0x00000000
};
static const gfx_img_t lambda78 = {
    .data = lambda78_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda79_data[] = {
    0x00000000,
    0x000001F0,
    0x000003F8,
    0x0000060C,
    0x00000404,
    0x0000060C,
    0x000003F8,
    0x000001F0,
    0x00000000
};
static const gfx_img_t lambda79 = {
    .data = lambda79_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda80_data[] = {
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000444,
    0x00000044,
    0x0000007C,
    0x00000038,
    0x00000000
};
static const gfx_img_t lambda80 = {
    .data = lambda80_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda81_data[] = {
    0x00000000,
    0x000001F8,
    0x000003FC,
    0x00000204,
    0x00000384,
    0x00000F04,
    0x00000FFC,
    0x000009F8,
    0x00000000
};
static const gfx_img_t lambda81 = {
    .data = lambda81_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda82_data[] = {
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000044,
    0x000000C4,
    0x000007FC,
    0x00000738,
    0x00000000
};
static const gfx_img_t lambda82 = {
    .data = lambda82_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda83_data[] = {
    0x00000000,
    0x00000318,
    0x0000073C,
    0x00000464,
    0x00000444,
    0x000004C4,
    0x0000079C,
    0x00000318,
    0x00000000
};
static const gfx_img_t lambda83 = {
    .data = lambda83_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda84_data[] = {
    0x0000001C,
    0x0000000C,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000404,
    0x0000000C,
    0x0000001C,
    0x00000000
};
static const gfx_img_t lambda84 = {
    .data = lambda84_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda85_data[] = {
    0x00000000,
    0x000003FC,
    0x000007FC,
    0x00000400,
    0x00000400,
    0x00000400,
    0x000007FC,
    0x000003FC,
    0x00000000
};
static const gfx_img_t lambda85 = {
    .data = lambda85_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda86_data[] = {
    0x000000FC,
    0x000001FC,
    0x00000300,
    0x00000600,
    0x00000600,
    0x00000300,
    0x000001FC,
    0x000000FC,
    0x00000000
};
static const gfx_img_t lambda86 = {
    .data = lambda86_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda87_data[] = {
    0x000001FC,
    0x000007FC,
    0x00000700,
    0x000001C0,
    0x000001C0,
    0x00000700,
    0x000007FC,
    0x000001FC,
    0x00000000
};
static const gfx_img_t lambda87 = {
    .data = lambda87_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda88_data[] = {
    0x0000060C,
    0x0000071C,
    0x000001B0,
    0x000000E0,
    0x000000E0,
    0x000001B0,
    0x0000071C,
    0x0000060C,
    0x00000000
};
static const gfx_img_t lambda88 = {
    .data = lambda88_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda89_data[] = {
    0x0000001C,
    0x0000003C,
    0x00000460,
    0x000007C0,
    0x000007C0,
    0x00000460,
    0x0000003C,
    0x0000001C,
    0x00000000
};
static const gfx_img_t lambda89 = {
    .data = lambda89_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda90_data[] = {
    0x0000061C,
    0x0000070C,
    0x00000584,
    0x000004C4,
    0x00000464,
    0x00000434,
    0x0000061C,
    0x0000070C,
    0x00000000
};
static const gfx_img_t lambda90 = {
    .data = lambda90_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda91_data[] = {
    0x00000000,
    0x00000000,
    0x000007FC,
    0x000007FC,
    0x00000404,
    0x00000404,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda91 = {
    .data = lambda91_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda92_data[] = {
    0x00000000,
    0x0000001C,
    0x00000038,
    0x00000070,
    0x000000E0,
    0x000001C0,
    0x00000380,
    0x00000700,
    0x00000000
};
static const gfx_img_t lambda92 = {
    .data = lambda92_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda93_data[] = {
    0x00000000,
    0x00000000,
    0x00000404,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda93 = {
    .data = lambda93_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda94_data[] = {
    0x00000000,
    0x00000008,
    0x0000000C,
    0x00000006,
    0x00000003,
    0x00000006,
    0x0000000C,
    0x00000008,
    0x00000000
};
static const gfx_img_t lambda94 = {
    .data = lambda94_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda95_data[] = {
    0x00001000,
    0x00001000,
    0x00001000,
    0x00001000,
    0x00001000,
    0x00001000,
    0x00001000,
    0x00001000,
    0x00000000
};
static const gfx_img_t lambda95 = {
    .data = lambda95_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda96_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000003,
    0x00000007,
    0x00000004,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda96 = {
    .data = lambda96_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda97_data[] = {
    0x00000000,
    0x00000300,
    0x000007A0,
    0x000004A0,
    0x000004A0,
    0x000003E0,
    0x000007C0,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda97 = {
    .data = lambda97_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda98_data[] = {
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000003FC,
    0x00000420,
    0x00000460,
    0x000007C0,
    0x00000380,
    0x00000000
};
static const gfx_img_t lambda98 = {
    .data = lambda98_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda99_data[] = {
    0x00000000,
    0x000003C0,
    0x000007E0,
    0x00000420,
    0x00000420,
    0x00000420,
    0x00000660,
    0x00000240,
    0x00000000
};
static const gfx_img_t lambda99 = {
    .data = lambda99_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda100_data[] = {
    0x00000000,
    0x00000380,
    0x000007C0,
    0x00000460,
    0x00000424,
    0x000003FC,
    0x000007FC,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda100 = {
    .data = lambda100_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda101_data[] = {
    0x00000000,
    0x000003C0,
    0x000007E0,
    0x000004A0,
    0x000004A0,
    0x000004A0,
    0x000006E0,
    0x000002C0,
    0x00000000
};
static const gfx_img_t lambda101 = {
    .data = lambda101_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda102_data[] = {
    0x00000000,
    0x00000440,
    0x000007F8,
    0x000007FC,
    0x00000444,
    0x0000004C,
    0x00000018,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda102 = {
    .data = lambda102_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda103_data[] = {
    0x00000000,
    0x000009C0,
    0x00001BE0,
    0x00001220,
    0x00001220,
    0x00001FC0,
    0x00000FE0,
    0x00000020,
    0x00000000
};
static const gfx_img_t lambda103 = {
    .data = lambda103_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda104_data[] = {
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000040,
    0x00000020,
    0x000007E0,
    0x000007C0,
    0x00000000
};
static const gfx_img_t lambda104 = {
    .data = lambda104_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda105_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000420,
    0x000007EC,
    0x000007EC,
    0x00000400,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda105 = {
    .data = lambda105_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda106_data[] = {
    0x00000000,
    0x00000C00,
    0x00001C00,
    0x00001000,
    0x00001020,
    0x00001FEC,
    0x00000FEC,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda106 = {
    .data = lambda106_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda107_data[] = {
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000080,
    0x000001C0,
    0x00000760,
    0x00000620,
    0x00000000
};
static const gfx_img_t lambda107 = {
    .data = lambda107_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda108_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000404,
    0x000007FC,
    0x000007FC,
    0x00000400,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda108 = {
    .data = lambda108_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda109_data[] = {
    0x000007E0,
    0x000007E0,
    0x00000060,
    0x000007C0,
    0x000007C0,
    0x00000060,
    0x000007E0,
    0x000007C0,
    0x00000000
};
static const gfx_img_t lambda109 = {
    .data = lambda109_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda110_data[] = {
    0x00000000,
    0x00000020,
    0x000007E0,
    0x000007C0,
    0x00000020,
    0x00000020,
    0x000007E0,
    0x000007C0,
    0x00000000
};
static const gfx_img_t lambda110 = {
    .data = lambda110_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda111_data[] = {
    0x00000000,
    0x000003C0,
    0x000007E0,
    0x00000420,
    0x00000420,
    0x00000420,
    0x000007E0,
    0x000003C0,
    0x00000000
};
static const gfx_img_t lambda111 = {
    .data = lambda111_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda112_data[] = {
    0x00000000,
    0x00001020,
    0x00001FE0,
    0x00001FC0,
    0x00001220,
    0x00000220,
    0x000003E0,
    0x000001C0,
    0x00000000
};
static const gfx_img_t lambda112 = {
    .data = lambda112_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda113_data[] = {
    0x00000000,
    0x000001C0,
    0x000003E0,
    0x00000220,
    0x00001220,
    0x00001FC0,
    0x00001FE0,
    0x00001020,
    0x00000000
};
static const gfx_img_t lambda113 = {
    .data = lambda113_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda114_data[] = {
    0x00000000,
    0x00000420,
    0x000007E0,
    0x000007C0,
    0x00000460,
    0x00000020,
    0x000000E0,
    0x000000C0,
    0x00000000
};
static const gfx_img_t lambda114 = {
    .data = lambda114_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda115_data[] = {
    0x00000000,
    0x00000240,
    0x000006E0,
    0x000004A0,
    0x000005A0,
    0x00000520,
    0x00000760,
    0x00000240,
    0x00000000
};
static const gfx_img_t lambda115 = {
    .data = lambda115_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda116_data[] = {
    0x00000000,
    0x00000020,
    0x00000020,
    0x000003F8,
    0x000007FC,
    0x00000420,
    0x00000620,
    0x00000200,
    0x00000000
};
static const gfx_img_t lambda116 = {
    .data = lambda116_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda117_data[] = {
    0x00000000,
    0x000003E0,
    0x000007E0,
    0x00000400,
    0x00000400,
    0x000003E0,
    0x000007E0,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda117 = {
    .data = lambda117_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda118_data[] = {
    0x000000E0,
    0x000001E0,
    0x00000300,
    0x00000600,
    0x00000600,
    0x00000300,
    0x000001E0,
    0x000000E0,
    0x00000000
};
static const gfx_img_t lambda118 = {
    .data = lambda118_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda119_data[] = {
    0x000003E0,
    0x000007E0,
    0x00000600,
    0x00000380,
    0x00000380,
    0x00000600,
    0x000007E0,
    0x000003E0,
    0x00000000
};
static const gfx_img_t lambda119 = {
    .data = lambda119_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda120_data[] = {
    0x00000000,
    0x00000420,
    0x00000660,
    0x000003C0,
    0x00000180,
    0x000003C0,
    0x00000660,
    0x00000420,
    0x00000000
};
static const gfx_img_t lambda120 = {
    .data = lambda120_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda121_data[] = {
    0x00000000,
    0x000001E0,
    0x000013E0,
    0x00001200,
    0x00001200,
    0x00001A00,
    0x00000FE0,
    0x000007E0,
    0x00000000
};
static const gfx_img_t lambda121 = {
    .data = lambda121_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda122_data[] = {
    0x00000000,
    0x00000460,
    0x00000660,
    0x00000720,
    0x000005A0,
    0x000004E0,
    0x00000660,
    0x00000620,
    0x00000000
};
static const gfx_img_t lambda122 = {
    .data = lambda122_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda123_data[] = {
    0x00000000,
    0x00000040,
    0x00000040,
    0x000003F8,
    0x000007BC,
    0x00000404,
    0x00000404,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda123 = {
    .data = lambda123_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda124_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x000007BC,
    0x000007BC,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda124 = {
    .data = lambda124_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda125_data[] = {
    0x00000000,
    0x00000404,
    0x00000404,
    0x000007BC,
    0x000003F8,
    0x00000040,
    0x00000040,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda125 = {
    .data = lambda125_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda126_data[] = {
    0x00000000,
    0x00000008,
    0x0000000C,
    0x00000004,
    0x0000000C,
    0x00000008,
    0x0000000C,
    0x00000004,
    0x00000000
};
static const gfx_img_t lambda126 = {
    .data = lambda126_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda127_data[] = {
    0x00000000,
    0x00000380,
    0x000003C0,
    0x00000260,
    0x00000230,
    0x00000260,
    0x000003C0,
    0x00000380,
    0x00000000
};
static const gfx_img_t lambda127 = {
    .data = lambda127_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda128_data[] = {
    0x00000000,
    0x000000F0,
    0x000011F8,
    0x0000130C,
    0x00001204,
    0x00001604,
    0x00001F0C,
    0x00000998,
    0x00000000
};
static const gfx_img_t lambda128 = {
    .data = lambda128_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda129_data[] = {
    0x00000000,
    0x000003EC,
    0x000007EC,
    0x00000400,
    0x00000400,
    0x000003EC,
    0x000007EC,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda129 = {
    .data = lambda129_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda130_data[] = {
    0x00000000,
    0x000003C0,
    0x000007E0,
    0x000004A8,
    0x000004AC,
    0x000004A6,
    0x000006E2,
    0x000002C0,
    0x00000000
};
static const gfx_img_t lambda130 = {
    .data = lambda130_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda131_data[] = {
    0x00000000,
    0x00000300,
    0x000007A8,
    0x000004AC,
    0x000004A6,
    0x000003EC,
    0x000007C8,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda131 = {
    .data = lambda131_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda132_data[] = {
    0x00000000,
    0x0000030C,
    0x000007AC,
    0x000004A0,
    0x000004A0,
    0x000003EC,
    0x000007CC,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda132 = {
    .data = lambda132_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda133_data[] = {
    0x00000000,
    0x00000300,
    0x000007A2,
    0x000004A6,
    0x000004AC,
    0x000003E8,
    0x000007C0,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda133 = {
    .data = lambda133_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda134_data[] = {
    0x00000000,
    0x00000300,
    0x000007A4,
    0x000004AE,
    0x000004AA,
    0x000003EE,
    0x000007C4,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda134 = {
    .data = lambda134_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda135_data[] = {
    0x00000000,
    0x000000E0,
    0x000009F0,
    0x00000910,
    0x00000B10,
    0x00000FB0,
    0x000004A0,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda135 = {
    .data = lambda135_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda136_data[] = {
    0x00000000,
    0x000003C0,
    0x000007E8,
    0x000004AC,
    0x000004A6,
    0x000004AC,
    0x000006E8,
    0x000002C0,
    0x00000000
};
static const gfx_img_t lambda136 = {
    .data = lambda136_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda137_data[] = {
    0x00000000,
    0x000003CC,
    0x000007EC,
    0x000004A0,
    0x000004A0,
    0x000004AC,
    0x000006EC,
    0x000002C0,
    0x00000000
};
static const gfx_img_t lambda137 = {
    .data = lambda137_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda138_data[] = {
    0x00000000,
    0x000003C0,
    0x000007E2,
    0x000004A6,
    0x000004AC,
    0x000004A8,
    0x000006E0,
    0x000002C0,
    0x00000000
};
static const gfx_img_t lambda138 = {
    .data = lambda138_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda139_data[] = {
    0x00000000,
    0x0000000C,
    0x0000042C,
    0x000007E0,
    0x000007E0,
    0x0000040C,
    0x0000000C,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda139 = {
    .data = lambda139_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda140_data[] = {
    0x00000000,
    0x00000008,
    0x0000042C,
    0x000007E6,
    0x000007E6,
    0x0000040C,
    0x00000008,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda140 = {
    .data = lambda140_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda141_data[] = {
    0x00000000,
    0x00000002,
    0x00000426,
    0x000007EC,
    0x000007E8,
    0x00000400,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda141 = {
    .data = lambda141_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda142_data[] = {
    0x00000000,
    0x000007C6,
    0x000007E6,
    0x00000130,
    0x00000118,
    0x00000130,
    0x000007E6,
    0x000007C6,
    0x00000000
};
static const gfx_img_t lambda142 = {
    .data = lambda142_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda143_data[] = {
    0x00000000,
    0x000007C0,
    0x000007E2,
    0x00000137,
    0x00000115,
    0x00000137,
    0x000007E2,
    0x000007C0,
    0x00000000
};
static const gfx_img_t lambda143 = {
    .data = lambda143_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda144_data[] = {
    0x00000000,
    0x00000410,
    0x000007F4,
    0x000007F6,
    0x00000493,
    0x00000491,
    0x000006B0,
    0x00000630,
    0x00000000
};
static const gfx_img_t lambda144 = {
    .data = lambda144_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda145_data[] = {
    0x00000300,
    0x00000790,
    0x000004B0,
    0x000007E0,
    0x000003F0,
    0x00000690,
    0x000004F0,
    0x00000460,
    0x00000000
};
static const gfx_img_t lambda145 = {
    .data = lambda145_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda146_data[] = {
    0x00000000,
    0x000007F0,
    0x000007F8,
    0x0000004C,
    0x00000044,
    0x000007FC,
    0x000007FC,
    0x00000444,
    0x00000000
};
static const gfx_img_t lambda146 = {
    .data = lambda146_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda147_data[] = {
    0x00000000,
    0x000003C0,
    0x000007E8,
    0x0000042C,
    0x00000426,
    0x0000042C,
    0x000007E8,
    0x000003C0,
    0x00000000
};
static const gfx_img_t lambda147 = {
    .data = lambda147_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda148_data[] = {
    0x00000000,
    0x000003CC,
    0x000007EC,
    0x00000420,
    0x00000420,
    0x00000420,
    0x000007EC,
    0x000003CC,
    0x00000000
};
static const gfx_img_t lambda148 = {
    .data = lambda148_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda149_data[] = {
    0x00000000,
    0x000003C0,
    0x000007E2,
    0x00000426,
    0x0000042C,
    0x00000428,
    0x000007E0,
    0x000003C0,
    0x00000000
};
static const gfx_img_t lambda149 = {
    .data = lambda149_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda150_data[] = {
    0x00000000,
    0x000003E8,
    0x000007EC,
    0x00000406,
    0x00000406,
    0x000003EC,
    0x000007E8,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda150 = {
    .data = lambda150_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda151_data[] = {
    0x00000000,
    0x000003E0,
    0x000007E2,
    0x00000406,
    0x0000040C,
    0x000003E8,
    0x000007E0,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda151 = {
    .data = lambda151_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda152_data[] = {
    0x00000000,
    0x000001EC,
    0x000013EC,
    0x00001200,
    0x00001200,
    0x00001A00,
    0x00000FEC,
    0x000007EC,
    0x00000000
};
static const gfx_img_t lambda152 = {
    .data = lambda152_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda153_data[] = {
    0x00000000,
    0x000001E6,
    0x000003F6,
    0x00000618,
    0x00000408,
    0x00000618,
    0x000003F6,
    0x000001E6,
    0x00000000
};
static const gfx_img_t lambda153 = {
    .data = lambda153_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda154_data[] = {
    0x00000000,
    0x000003F6,
    0x000007F6,
    0x00000400,
    0x00000400,
    0x00000400,
    0x000007F6,
    0x000003F6,
    0x00000000
};
static const gfx_img_t lambda154 = {
    .data = lambda154_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda155_data[] = {
    0x000000F0,
    0x000001F8,
    0x00000108,
    0x0000070E,
    0x0000070E,
    0x00000108,
    0x00000198,
    0x00000090,
    0x00000000
};
static const gfx_img_t lambda155 = {
    .data = lambda155_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda156_data[] = {
    0x00000000,
    0x00000620,
    0x000007FC,
    0x000007FE,
    0x00000422,
    0x00000406,
    0x0000060C,
    0x00000200,
    0x00000000
};
static const gfx_img_t lambda156 = {
    .data = lambda156_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda157_data[] = {
    0x00000144,
    0x0000014C,
    0x00000158,
    0x000007F0,
    0x000007F0,
    0x00000158,
    0x0000014C,
    0x00000144,
    0x00000000
};
static const gfx_img_t lambda157 = {
    .data = lambda157_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda158_data[] = {
    0x00000402,
    0x000007FE,
    0x000007FE,
    0x00000412,
    0x00000092,
    0x000003DE,
    0x000007EC,
    0x00000480,
    0x00000000
};
static const gfx_img_t lambda158 = {
    .data = lambda158_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda159_data[] = {
    0x00000800,
    0x00001840,
    0x00001040,
    0x00001FFC,
    0x00000FFE,
    0x00000042,
    0x00000046,
    0x00000004,
    0x00000000
};
static const gfx_img_t lambda159 = {
    .data = lambda159_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda160_data[] = {
    0x00000000,
    0x00000300,
    0x000007A8,
    0x000004AC,
    0x000004A6,
    0x000003E2,
    0x000007C0,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda160 = {
    .data = lambda160_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda161_data[] = {
    0x00000000,
    0x00000000,
    0x00000428,
    0x000007EC,
    0x000007E6,
    0x00000402,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda161 = {
    .data = lambda161_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda162_data[] = {
    0x00000000,
    0x000003C0,
    0x000007E8,
    0x0000042C,
    0x00000426,
    0x00000422,
    0x000007E0,
    0x000003C0,
    0x00000000
};
static const gfx_img_t lambda162 = {
    .data = lambda162_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda163_data[] = {
    0x00000000,
    0x000003E0,
    0x000007E8,
    0x0000040C,
    0x00000406,
    0x000003E2,
    0x000007E0,
    0x00000400,
    0x00000000
};
static const gfx_img_t lambda163 = {
    .data = lambda163_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda164_data[] = {
    0x00000000,
    0x00000028,
    0x000007EC,
    0x000007C4,
    0x0000002C,
    0x00000028,
    0x000007EC,
    0x000007C4,
    0x00000000
};
static const gfx_img_t lambda164 = {
    .data = lambda164_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda165_data[] = {
    0x00000000,
    0x000007FA,
    0x000007FB,
    0x00000071,
    0x000000E3,
    0x000001C2,
    0x000007FB,
    0x000007F9,
    0x00000000
};
static const gfx_img_t lambda165 = {
    .data = lambda165_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda166_data[] = {
    0x00000000,
    0x0000004C,
    0x0000005E,
    0x00000052,
    0x0000005E,
    0x0000005E,
    0x00000050,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda166 = {
    .data = lambda166_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda167_data[] = {
    0x00000000,
    0x0000004C,
    0x0000005E,
    0x00000052,
    0x0000005E,
    0x0000004C,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda167 = {
    .data = lambda167_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda168_data[] = {
    0x00000000,
    0x00000300,
    0x00000780,
    0x000004EC,
    0x0000046C,
    0x00000400,
    0x00000700,
    0x00000300,
    0x00000000
};
static const gfx_img_t lambda168 = {
    .data = lambda168_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda169_data[] = {
    0x00000000,
    0x000003C0,
    0x000003C0,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000000
};
static const gfx_img_t lambda169 = {
    .data = lambda169_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda170_data[] = {
    0x00000000,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000040,
    0x000003C0,
    0x000003C0,
    0x00000000
};
static const gfx_img_t lambda170 = {
    .data = lambda170_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda171_data[] = {
    0x00000204,
    0x0000033E,
    0x000001BE,
    0x000010C0,
    0x00001960,
    0x00001D30,
    0x00001718,
    0x00001208,
    0x00000000
};
static const gfx_img_t lambda171 = {
    .data = lambda171_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda172_data[] = {
    0x00000204,
    0x0000033E,
    0x000001BE,
    0x000004C0,
    0x00000660,
    0x00000730,
    0x00001F98,
    0x00001F88,
    0x00000000
};
static const gfx_img_t lambda172 = {
    .data = lambda172_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda173_data[] = {
    0x00000000,
    0x00000000,
    0x00000380,
    0x000007EC,
    0x000007EC,
    0x00000380,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda173 = {
    .data = lambda173_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda174_data[] = {
    0x00000000,
    0x00000040,
    0x000000E0,
    0x000001B0,
    0x00000150,
    0x000000E0,
    0x000001B0,
    0x00000110,
    0x00000000
};
static const gfx_img_t lambda174 = {
    .data = lambda174_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda175_data[] = {
    0x00000000,
    0x00000110,
    0x000001B0,
    0x000000E0,
    0x00000150,
    0x000001B0,
    0x000000E0,
    0x00000040,
    0x00000000
};
static const gfx_img_t lambda175 = {
    .data = lambda175_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda176_data[] = {
    0x00000000,
    0x00002AAA,
    0x00000000,
    0x00001555,
    0x00000000,
    0x00002AAA,
    0x00000000,
    0x00001555,
    0x00000000
};
static const gfx_img_t lambda176 = {
    .data = lambda176_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda177_data[] = {
    0x00002AAA,
    0x00001555,
    0x00002AAA,
    0x00001555,
    0x00002AAA,
    0x00001555,
    0x00002AAA,
    0x00001555,
    0x00000000
};
static const gfx_img_t lambda177 = {
    .data = lambda177_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda178_data[] = {
    0x00001555,
    0x00003FFF,
    0x00002AAA,
    0x00003FFF,
    0x00001555,
    0x00003FFF,
    0x00002AAA,
    0x00003FFF,
    0x00000000
};
static const gfx_img_t lambda178 = {
    .data = lambda178_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda179_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00003FFF,
    0x00003FFF,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda179 = {
    .data = lambda179_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda180_data[] = {
    0x00000080,
    0x00000080,
    0x00000080,
    0x00003FFF,
    0x00003FFF,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda180 = {
    .data = lambda180_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda181_data[] = {
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x00003FFF,
    0x00003FFF,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda181 = {
    .data = lambda181_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda182_data[] = {
    0x00000080,
    0x00000080,
    0x00003FFF,
    0x00003FFF,
    0x00000000,
    0x00003FFF,
    0x00003FFF,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda182 = {
    .data = lambda182_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda183_data[] = {
    0x00000080,
    0x00000080,
    0x00003F80,
    0x00003F80,
    0x00000080,
    0x00003F80,
    0x00003F80,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda183 = {
    .data = lambda183_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda184_data[] = {
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x00003FE0,
    0x00003FE0,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda184 = {
    .data = lambda184_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda185_data[] = {
    0x000000A0,
    0x000000A0,
    0x00003FBF,
    0x00003FBF,
    0x00000000,
    0x00003FFF,
    0x00003FFF,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda185 = {
    .data = lambda185_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda186_data[] = {
    0x00000000,
    0x00000000,
    0x00003FFF,
    0x00003FFF,
    0x00000000,
    0x00003FFF,
    0x00003FFF,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda186 = {
    .data = lambda186_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda187_data[] = {
    0x000000A0,
    0x000000A0,
    0x00003FA0,
    0x00003FA0,
    0x00000020,
    0x00003FE0,
    0x00003FE0,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda187 = {
    .data = lambda187_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda188_data[] = {
    0x000000A0,
    0x000000A0,
    0x000000BF,
    0x000000BF,
    0x00000080,
    0x000000FF,
    0x000000FF,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda188 = {
    .data = lambda188_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda189_data[] = {
    0x00000080,
    0x00000080,
    0x000000FF,
    0x000000FF,
    0x00000080,
    0x000000FF,
    0x000000FF,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda189 = {
    .data = lambda189_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda190_data[] = {
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000FF,
    0x000000FF,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda190 = {
    .data = lambda190_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda191_data[] = {
    0x00000080,
    0x00000080,
    0x00000080,
    0x00003F80,
    0x00003F80,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda191 = {
    .data = lambda191_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda192_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x000000FF,
    0x000000FF,
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda192 = {
    .data = lambda192_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda193_data[] = {
    0x00000080,
    0x00000080,
    0x00000080,
    0x000000FF,
    0x000000FF,
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda193 = {
    .data = lambda193_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda194_data[] = {
    0x00000080,
    0x00000080,
    0x00000080,
    0x00003F80,
    0x00003F80,
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda194 = {
    .data = lambda194_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda195_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00003FFF,
    0x00003FFF,
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda195 = {
    .data = lambda195_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda196_data[] = {
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda196 = {
    .data = lambda196_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda197_data[] = {
    0x00000080,
    0x00000080,
    0x00000080,
    0x00003FFF,
    0x00003FFF,
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda197 = {
    .data = lambda197_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda198_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00003FFF,
    0x00003FFF,
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda198 = {
    .data = lambda198_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda199_data[] = {
    0x00000000,
    0x00000000,
    0x00003FFF,
    0x00003FFF,
    0x00000000,
    0x00003FFF,
    0x00003FFF,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda199 = {
    .data = lambda199_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda200_data[] = {
    0x00000000,
    0x00000000,
    0x000000FF,
    0x000000FF,
    0x00000080,
    0x000000BF,
    0x000000BF,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda200 = {
    .data = lambda200_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda201_data[] = {
    0x00000000,
    0x00000000,
    0x00003FE0,
    0x00003FE0,
    0x00000020,
    0x00003FA0,
    0x00003FA0,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda201 = {
    .data = lambda201_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda202_data[] = {
    0x000000A0,
    0x000000A0,
    0x000000BF,
    0x000000BF,
    0x00000080,
    0x000000BF,
    0x000000BF,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda202 = {
    .data = lambda202_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda203_data[] = {
    0x000000A0,
    0x000000A0,
    0x00003FA0,
    0x00003FA0,
    0x00000020,
    0x00003FA0,
    0x00003FA0,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda203 = {
    .data = lambda203_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda204_data[] = {
    0x00000000,
    0x00000000,
    0x00003FFF,
    0x00003FFF,
    0x00000000,
    0x00003FBF,
    0x00003FBF,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda204 = {
    .data = lambda204_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda205_data[] = {
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda205 = {
    .data = lambda205_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda206_data[] = {
    0x000000A0,
    0x000000A0,
    0x00003FBF,
    0x00003FBF,
    0x00000000,
    0x00003FBF,
    0x00003FBF,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda206 = {
    .data = lambda206_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda207_data[] = {
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000BF,
    0x000000BF,
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda207 = {
    .data = lambda207_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda208_data[] = {
    0x00000080,
    0x00000080,
    0x000000FF,
    0x000000FF,
    0x00000080,
    0x000000FF,
    0x000000FF,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda208 = {
    .data = lambda208_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda209_data[] = {
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x00003FA0,
    0x00003FA0,
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda209 = {
    .data = lambda209_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda210_data[] = {
    0x00000080,
    0x00000080,
    0x00003F80,
    0x00003F80,
    0x00000080,
    0x00003F80,
    0x00003F80,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda210 = {
    .data = lambda210_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda211_data[] = {
    0x00000000,
    0x00000000,
    0x000000FF,
    0x000000FF,
    0x00000080,
    0x000000FF,
    0x000000FF,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda211 = {
    .data = lambda211_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda212_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x000000FF,
    0x000000FF,
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda212 = {
    .data = lambda212_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda213_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00003FE0,
    0x00003FE0,
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda213 = {
    .data = lambda213_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda214_data[] = {
    0x00000000,
    0x00000000,
    0x00003F80,
    0x00003F80,
    0x00000080,
    0x00003F80,
    0x00003F80,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda214 = {
    .data = lambda214_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda215_data[] = {
    0x00000080,
    0x00000080,
    0x00003FFF,
    0x00003FFF,
    0x00000080,
    0x00003FFF,
    0x00003FFF,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda215 = {
    .data = lambda215_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda216_data[] = {
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x00003FFF,
    0x00003FFF,
    0x000000A0,
    0x000000A0,
    0x000000A0,
    0x000000A0
};
static const gfx_img_t lambda216 = {
    .data = lambda216_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda217_data[] = {
    0x00000080,
    0x00000080,
    0x00000080,
    0x000000FF,
    0x000000FF,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda217 = {
    .data = lambda217_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda218_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00003F80,
    0x00003F80,
    0x00000080,
    0x00000080,
    0x00000080,
    0x00000080
};
static const gfx_img_t lambda218 = {
    .data = lambda218_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda219_data[] = {
    0x00003FFF,
    0x00003FFF,
    0x00003FFF,
    0x00003FFF,
    0x00003FFF,
    0x00003FFF,
    0x00003FFF,
    0x00003FFF,
    0x00003FFF
};
static const gfx_img_t lambda219 = {
    .data = lambda219_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda220_data[] = {
    0x00003F80,
    0x00003F80,
    0x00003F80,
    0x00003F80,
    0x00003F80,
    0x00003F80,
    0x00003F80,
    0x00003F80,
    0x00003F80
};
static const gfx_img_t lambda220 = {
    .data = lambda220_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda221_data[] = {
    0x00003FFF,
    0x00003FFF,
    0x00003FFF,
    0x00003FFF,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda221 = {
    .data = lambda221_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda222_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00003FFF,
    0x00003FFF,
    0x00003FFF,
    0x00003FFF,
    0x00003FFF
};
static const gfx_img_t lambda222 = {
    .data = lambda222_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda223_data[] = {
    0x0000007F,
    0x0000007F,
    0x0000007F,
    0x0000007F,
    0x0000007F,
    0x0000007F,
    0x0000007F,
    0x0000007F,
    0x0000007F
};
static const gfx_img_t lambda223 = {
    .data = lambda223_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda224_data[] = {
    0x00000000,
    0x000003C0,
    0x000007E0,
    0x00000420,
    0x000007E0,
    0x000003C0,
    0x00000660,
    0x00000420,
    0x00000000
};
static const gfx_img_t lambda224 = {
    .data = lambda224_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda225_data[] = {
    0x00000000,
    0x00000FE0,
    0x00001FF0,
    0x00000250,
    0x00000250,
    0x00000250,
    0x000003F0,
    0x000001A0,
    0x00000000
};
static const gfx_img_t lambda225 = {
    .data = lambda225_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda226_data[] = {
    0x00000000,
    0x000007FC,
    0x000007FC,
    0x00000004,
    0x00000004,
    0x00000004,
    0x0000001C,
    0x0000001C,
    0x00000000
};
static const gfx_img_t lambda226 = {
    .data = lambda226_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda227_data[] = {
    0x00000000,
    0x00000010,
    0x000007F0,
    0x000007F0,
    0x00000010,
    0x000007F0,
    0x000007F0,
    0x00000010,
    0x00000000
};
static const gfx_img_t lambda227 = {
    .data = lambda227_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda228_data[] = {
    0x00000000,
    0x0000060C,
    0x0000071C,
    0x000005B4,
    0x000004E4,
    0x00000444,
    0x0000060C,
    0x0000060C,
    0x00000000
};
static const gfx_img_t lambda228 = {
    .data = lambda228_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda229_data[] = {
    0x00000000,
    0x000003C0,
    0x000007E0,
    0x00000420,
    0x000007E0,
    0x000003E0,
    0x00000020,
    0x00000020,
    0x00000000
};
static const gfx_img_t lambda229 = {
    .data = lambda229_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda230_data[] = {
    0x00000000,
    0x00000800,
    0x00000FF0,
    0x000007F0,
    0x00000100,
    0x00000100,
    0x000001F0,
    0x000000F0,
    0x00000000
};
static const gfx_img_t lambda230 = {
    .data = lambda230_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda231_data[] = {
    0x00000000,
    0x00000020,
    0x00000030,
    0x00000010,
    0x000007F0,
    0x000007E0,
    0x00000030,
    0x00000010,
    0x00000000
};
static const gfx_img_t lambda231 = {
    .data = lambda231_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda232_data[] = {
    0x00000000,
    0x000004E4,
    0x000005F4,
    0x0000071C,
    0x0000071C,
    0x000005F4,
    0x000004E4,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda232 = {
    .data = lambda232_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda233_data[] = {
    0x00000000,
    0x000001F0,
    0x000003F8,
    0x0000064C,
    0x00000444,
    0x0000064C,
    0x000003F8,
    0x000001F0,
    0x00000000
};
static const gfx_img_t lambda233 = {
    .data = lambda233_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda234_data[] = {
    0x00000000,
    0x00000470,
    0x000007F8,
    0x0000078C,
    0x00000004,
    0x0000078C,
    0x000007F8,
    0x00000470,
    0x00000000
};
static const gfx_img_t lambda234 = {
    .data = lambda234_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda235_data[] = {
    0x00000000,
    0x00000380,
    0x000007C8,
    0x0000045C,
    0x00000474,
    0x000007E4,
    0x000003C4,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda235 = {
    .data = lambda235_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda236_data[] = {
    0x000000C0,
    0x000001E0,
    0x00000120,
    0x000001E0,
    0x000001E0,
    0x00000120,
    0x000001E0,
    0x000000C0,
    0x00000000
};
static const gfx_img_t lambda236 = {
    .data = lambda236_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda237_data[] = {
    0x000004E0,
    0x000007F0,
    0x00000390,
    0x000001F0,
    0x00000170,
    0x00000118,
    0x000001FC,
    0x000000E4,
    0x00000000
};
static const gfx_img_t lambda237 = {
    .data = lambda237_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda238_data[] = {
    0x00000000,
    0x000001F0,
    0x000003F8,
    0x0000064C,
    0x00000444,
    0x00000444,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda238 = {
    .data = lambda238_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda239_data[] = {
    0x00000000,
    0x000007F0,
    0x000007F8,
    0x00000008,
    0x00000008,
    0x00000008,
    0x000007F8,
    0x000007F0,
    0x00000000
};
static const gfx_img_t lambda239 = {
    .data = lambda239_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda240_data[] = {
    0x00000000,
    0x00000248,
    0x00000248,
    0x00000248,
    0x00000248,
    0x00000248,
    0x00000248,
    0x00000248,
    0x00000000
};
static const gfx_img_t lambda240 = {
    .data = lambda240_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda241_data[] = {
    0x00000420,
    0x00000420,
    0x00000420,
    0x000005FC,
    0x000005FC,
    0x00000420,
    0x00000420,
    0x00000420,
    0x00000000
};
static const gfx_img_t lambda241 = {
    .data = lambda241_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda242_data[] = {
    0x00000000,
    0x00000400,
    0x00000504,
    0x0000058C,
    0x000004D8,
    0x00000470,
    0x00000420,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda242 = {
    .data = lambda242_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda243_data[] = {
    0x00000000,
    0x00000420,
    0x00000470,
    0x000004D8,
    0x0000058C,
    0x00000504,
    0x00000400,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda243 = {
    .data = lambda243_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda244_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00003FF8,
    0x00003FFC,
    0x00000004,
    0x0000001C,
    0x00000018,
    0x00000000
};
static const gfx_img_t lambda244 = {
    .data = lambda244_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda245_data[] = {
    0x00000300,
    0x00000700,
    0x00000400,
    0x000007FF,
    0x000003FF,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda245 = {
    .data = lambda245_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda246_data[] = {
    0x00000040,
    0x00000040,
    0x00000040,
    0x0000064C,
    0x0000064C,
    0x00000040,
    0x00000040,
    0x00000040,
    0x00000000
};
static const gfx_img_t lambda246 = {
    .data = lambda246_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda247_data[] = {
    0x00000000,
    0x00000120,
    0x000001B0,
    0x00000090,
    0x000001B0,
    0x00000120,
    0x000001B0,
    0x00000090,
    0x00000000
};
static const gfx_img_t lambda247 = {
    .data = lambda247_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda248_data[] = {
    0x00000000,
    0x0000000C,
    0x0000001E,
    0x00000012,
    0x0000001E,
    0x0000000C,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda248 = {
    .data = lambda248_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda249_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x000000C0,
    0x000000C0,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda249 = {
    .data = lambda249_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda250_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000080,
    0x00000080,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda250 = {
    .data = lambda250_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda251_data[] = {
    0x00000080,
    0x00000180,
    0x00000380,
    0x00000600,
    0x000007FE,
    0x000007FE,
    0x00000002,
    0x00000002,
    0x00000000
};
static const gfx_img_t lambda251 = {
    .data = lambda251_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda252_data[] = {
    0x00000002,
    0x0000007E,
    0x0000007C,
    0x00000002,
    0x0000007E,
    0x0000007C,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda252 = {
    .data = lambda252_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda253_data[] = {
    0x00000064,
    0x00000076,
    0x0000005A,
    0x0000004E,
    0x00000064,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda253 = {
    .data = lambda253_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda254_data[] = {
    0x00000000,
    0x00000000,
    0x000003F0,
    0x000003F0,
    0x000003F0,
    0x000003F0,
    0x000003F0,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda254 = {
    .data = lambda254_data,
    .width = 9,
    .height = 14
};

static const uint64_t lambda255_data[] = {
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000
};
static const gfx_img_t lambda255 = {
    .data = lambda255_data,
    .width = 9,
    .height = 14
};

const gfx_font_t font_system_14 = {
    .glyph_width = 9,
    .glyph_height = 14,
    .padding_x = 2,
    .padding_y = 2,
    .glyph_data = {
        &lambda0,
        &lambda1,
        &lambda2,
        &lambda3,
        &lambda4,
        &lambda5,
        &lambda6,
        &lambda7,
        &lambda8,
        &lambda9,
        &lambda10,
        &lambda11,
        &lambda12,
        &lambda13,
        &lambda14,
        &lambda15,
        &lambda16,
        &lambda17,
        &lambda18,
        &lambda19,
        &lambda20,
        &lambda21,
        &lambda22,
        &lambda23,
        &lambda24,
        &lambda25,
        &lambda26,
        &lambda27,
        &lambda28,
        &lambda29,
        &lambda30,
        &lambda31,
        &lambda32,
        &lambda33,
        &lambda34,
        &lambda35,
        &lambda36,
        &lambda37,
        &lambda38,
        &lambda39,
        &lambda40,
        &lambda41,
        &lambda42,
        &lambda43,
        &lambda44,
        &lambda45,
        &lambda46,
        &lambda47,
        &lambda48,
        &lambda49,
        &lambda50,
        &lambda51,
        &lambda52,
        &lambda53,
        &lambda54,
        &lambda55,
        &lambda56,
        &lambda57,
        &lambda58,
        &lambda59,
        &lambda60,
        &lambda61,
        &lambda62,
        &lambda63,
        &lambda64,
        &lambda65,
        &lambda66,
        &lambda67,
        &lambda68,
        &lambda69,
        &lambda70,
        &lambda71,
        &lambda72,
        &lambda73,
        &lambda74,
        &lambda75,
        &lambda76,
        &lambda77,
        &lambda78,
        &lambda79,
        &lambda80,
        &lambda81,
        &lambda82,
        &lambda83,
        &lambda84,
        &lambda85,
        &lambda86,
        &lambda87,
        &lambda88,
        &lambda89,
        &lambda90,
        &lambda91,
        &lambda92,
        &lambda93,
        &lambda94,
        &lambda95,
        &lambda96,
        &lambda97,
        &lambda98,
        &lambda99,
        &lambda100,
        &lambda101,
        &lambda102,
        &lambda103,
        &lambda104,
        &lambda105,
        &lambda106,
        &lambda107,
        &lambda108,
        &lambda109,
        &lambda110,
        &lambda111,
        &lambda112,
        &lambda113,
        &lambda114,
        &lambda115,
        &lambda116,
        &lambda117,
        &lambda118,
        &lambda119,
        &lambda120,
        &lambda121,
        &lambda122,
        &lambda123,
        &lambda124,
        &lambda125,
        &lambda126,
        &lambda127,
        &lambda128,
        &lambda129,
        &lambda130,
        &lambda131,
        &lambda132,
        &lambda133,
        &lambda134,
        &lambda135,
        &lambda136,
        &lambda137,
        &lambda138,
        &lambda139,
        &lambda140,
        &lambda141,
        &lambda142,
        &lambda143,
        &lambda144,
        &lambda145,
        &lambda146,
        &lambda147,
        &lambda148,
        &lambda149,
        &lambda150,
        &lambda151,
        &lambda152,
        &lambda153,
        &lambda154,
        &lambda155,
        &lambda156,
        &lambda157,
        &lambda158,
        &lambda159,
        &lambda160,
        &lambda161,
        &lambda162,
        &lambda163,
        &lambda164,
        &lambda165,
        &lambda166,
        &lambda167,
        &lambda168,
        &lambda169,
        &lambda170,
        &lambda171,
        &lambda172,
        &lambda173,
        &lambda174,
        &lambda175,
        &lambda176,
        &lambda177,
        &lambda178,
        &lambda179,
        &lambda180,
        &lambda181,
        &lambda182,
        &lambda183,
        &lambda184,
        &lambda185,
        &lambda186,
        &lambda187,
        &lambda188,
        &lambda189,
        &lambda190,
        &lambda191,
        &lambda192,
        &lambda193,
        &lambda194,
        &lambda195,
        &lambda196,
        &lambda197,
        &lambda198,
        &lambda199,
        &lambda200,
        &lambda201,
        &lambda202,
        &lambda203,
        &lambda204,
        &lambda205,
        &lambda206,
        &lambda207,
        &lambda208,
        &lambda209,
        &lambda210,
        &lambda211,
        &lambda212,
        &lambda213,
        &lambda214,
        &lambda215,
        &lambda216,
        &lambda217,
        &lambda218,
        &lambda219,
        &lambda220,
        &lambda221,
        &lambda222,
        &lambda223,
        &lambda224,
        &lambda225,
        &lambda226,
        &lambda227,
        &lambda228,
        &lambda229,
        &lambda230,
        &lambda231,
        &lambda232,
        &lambda233,
        &lambda234,
        &lambda235,
        &lambda236,
        &lambda237,
        &lambda238,
        &lambda239,
        &lambda240,
        &lambda241,
        &lambda242,
        &lambda243,
        &lambda244,
        &lambda245,
        &lambda246,
        &lambda247,
        &lambda248,
        &lambda249,
        &lambda250,
        &lambda251,
        &lambda252,
        &lambda253,
        &lambda254,
        &lambda255
    }
};

static const uint64_t icon_sdcard_data[] = {
    0x00000000,
    0x00000FF0,
    0x00000808,
    0x00000804,
    0x00000802,
    0x0000080E,
    0x00000802,
    0x0000080E,
    0x00000802,
    0x00000FFE,
    0x00000000
};
const gfx_img_t icon_sdcard = {
    .data = icon_sdcard_data,
    .width = 11,
    .height = 13
};

static const uint64_t icon_sdcard_error_data[] = {
    0x00000000,
    0x00000FF0,
    0x00000808,
    0x00000004,
    0x00001802,
    0x00001E0E,
    0x00001F82,
    0x000014CE,
    0x00001F82,
    0x00001E1E,
    0x00001800
};
const gfx_img_t icon_sdcard_error = {
    .data = icon_sdcard_error_data,
    .width = 11,
    .height = 13
};

static const uint64_t icon_sdcard_none_data[] = {
    0x00000000,
    0x00000FF0,
    0x00000808,
    0x00000004,
    0x00001042,
    0x0000088E,
    0x00000502,
    0x0000020E,
    0x00000502,
    0x0000089E,
    0x00001040
};
const gfx_img_t icon_sdcard_none = {
    .data = icon_sdcard_none_data,
    .width = 11,
    .height = 13
};

static const uint64_t icon_sdcard_waiting_data[] = {
    0x00000000,
    0x00000FF0,
    0x00000808,
    0x00000004,
    0x00000702,
    0x0000088E,
    0x00001042,
    0x0000134E,
    0x00001242,
    0x0000089E,
    0x00000700
};
const gfx_img_t icon_sdcard_waiting = {
    .data = icon_sdcard_waiting_data,
    .width = 11,
    .height = 13
};

